name: Deploy to GitHub Pages

on:
  # 每次推送到 `main` 分支时触发这个“工作流程”
  push:
    branches: [ main ]
  # 允许你在 GitHub 上的 Actions 标签中手动触发此“工作流程”
  workflow_dispatch:

# 设置权限
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: 构建网站
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v5

      - name: 设置NodeJS
        uses: withastro/action@v5
        with:
          node-version: 24

  deploy:
    name: 部署到 GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
